name: Build Pipeline on the Unity Project

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2022.3.19f1-linux-il2cpp-3.0.1
    strategy:
      matrix:
        unity-version: [2022.3.19f1]
        platform: [ StandaloneOSX, StandaloneWindows64, StandaloneLinux64, WebGL ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with: 
          targetPlatform: ${{ matrix.platform }}
          buildMethod: Cgs.Editor.BuildCgs.BuildOptions
          unityVersion: ${{ matrix.unity-version }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: Build